version: 2.1
parameters:
  action:
    type: boolean
    default: false
jobs:
  plan-apply:
    working_directory: ~/lcm-sayu-infra
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform workspace new dev || terraform workspace select dev
            terraform plan -out terraform.out
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve terraform.out
      - persist_to_workspace:
          root: .
          paths:
            - .
  destroy:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform workspace select dev
            terraform destroy -auto-approve

workflows:
  deploy_infrastructure:
    when:
      condition:
        not: << pipeline.parameters.action >>
    jobs:
      - plan-apply
      - apply:
          filters:
            branches:
              only:
                - master
                - dev
                - pipeline
          requires:
            - plan-apply

  destroy_infrastructure:
    when: << pipeline.parameters.action >>
    jobs:
      - hold-destroy:
          type: approval
      - destroy:
          requires:
            - hold-destroy
